//
// Created by Ronan on 17/01/2021.
//

#ifndef FENETRAGE_REMPLISSAGE_POLYGONES_LCA_H
#define FENETRAGE_REMPLISSAGE_POLYGONES_LCA_H


class Lca {
};


#endif //FENETRAGE_REMPLISSAGE_POLYGONES_LCA_H
